package com.example.lab.model.enumeration;

public enum PrivilegeEnum {

    RESERVATION_CREATE_PRIVILEGE,
    RESERVATION_STATUS_UPDATE_PRIVILEGE,
    RESERVATION_DELETE_PRIVILEGE,
    RESERVATION_READ_PRIVILEGE,
    ROUTE_READ_PRIVILEGE,
    ROUTE_DELETE_PRIVILEGE,
    ROUTE_UPDATE_PRIVILEGE,
    TICKET_CREATE_PRIVILEGE,
    TICKET_READ_PRIVILEGE,
    TICKET_UPDATE_PRIVILEGE,
    TICKET_DELETE_PRIVILEGE,
    USER_READ_PRIVILEGE,
    USER_UPDATE_PRIVILEGE,
    USER_PROMOTE_PRIVILEGE,
    USER_EDIT_PRIVILEGE,
    RESERVATION_EDIT_PRIVILEGE;

}
