spring:
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s335148
    password: rzLbQbEEUx0WUqBv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
server:
  port: 22222