spring:
  r2dbc:
    url: r2dbc:postgresql://pg:5432/studs
    username: s335148
    password: rzLbQbEEUx0WUqBv
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:postgresql://pg:5432/studs
    user: s335148
    password: rzLbQbEEUx0WUqBv
server:
  port: 22222

jwt:
  secret:
    access:
      key: B6E5061FADAD40CCAEBDD0F4B3EB3DEE3F4FCE86695FA0076BA9E0A894A53140
      expiration: 9999999